### ISSUE TITLE
URDF failed Model parse

### ISSUE THREAD

**Issue by vkuehn** [benbongalon/ros2-urdf-tutorial#1]
First I tried manually and than I did download the complete example still I get in RVIZ the message "URDF failed Model parse". In RVIZ it shows the TF Axes and Arrows moving around but not the URDF Model.

Also I see this in the console.
Parsing robot urdf xml string.
Error:   length [.5] is not a valid float
         at line 183 in /tmp/binarydeb/ros-foxy-urdfdom-2.3.3/urdf_parser/src/link.cpp
Error:   Could not parse visual element for Link [axis]
         at line 495 in /tmp/binarydeb/ros-foxy-urdfdom-2.3.3/urdf_parser/src/link.cpp
Error:   length [.6] is not a valid float
         at line 183 in /tmp/binarydeb/ros-foxy-urdfdom-2.3.3/urdf_parser/src/link.cpp
Error:   Could not parse visual element for Link [body]
         at line 495 in /tmp/binarydeb/ros-foxy-urdfdom-2.3.3/urdf_parser/src/link.cpp
Error:   radius [.4] is not a valid float: stod
         at line 126 in /tmp/binarydeb/ros-foxy-urdfdom-2.3.3/urdf_parser/src/link.cpp
Error:   Could not parse visual element for Link [head]
         at line 495 in /tmp/binarydeb/ros-foxy-urdfdom-2.3.3/urdf_parser/src/link.cpp
Error:   length [.2] is not a valid float
         at line 183 in /tmp/binarydeb/ros-foxy-urdfdom-2.3.3/urdf_parser/src/link.cpp
Error:   Could not parse visual element for Link [rod]
         at line 495 in /tmp/binarydeb/ros-foxy-urdfdom-2.3.3/urdf_parser/src/link.cpp
Error:   lower value (-.5) is not a float: stod
         at line 130 in /tmp/binarydeb/ros-foxy-urdfdom-2.3.3/urdf_parser/src/joint.cpp
Error:   Could not parse limit element for joint [tilt]
         at line 565 in /tmp/binarydeb/ros-foxy-urdfdom-2.3.3/urdf_parser/src/joint.cpp
Error:   joint xml is not initialized correctly
         at line 206 in /tmp/binarydeb/ros-foxy-urdfdom-2.3.3/urdf_parser/src/model.cpp
Parsing robot urdf xml string.
Error:   length [.5] is not a valid float
         at line 183 in /tmp/binarydeb/ros-foxy-urdfdom-2.3.3/urdf_parser/src/link.cpp
Error:   Could not parse visual element for Link [axis]
         at line 495 in /tmp/binarydeb/ros-foxy-urdfdom-2.3.3/urdf_parser/src/link.cpp
Error:   length [.6] is not a valid float
         at line 183 in /tmp/binarydeb/ros-foxy-urdfdom-2.3.3/urdf_parser/src/link.cpp
Error:   Could not parse visual element for Link [body]
         at line 495 in /tmp/binarydeb/ros-foxy-urdfdom-2.3.3/urdf_parser/src/link.cpp
Error:   radius [.4] is not a valid float: stod
         at line 126 in /tmp/binarydeb/ros-foxy-urdfdom-2.3.3/urdf_parser/src/link.cpp
Error:   Could not parse visual element for Link [head]
         at line 495 in /tmp/binarydeb/ros-foxy-urdfdom-2.3.3/urdf_parser/src/link.cpp
Error:   length [.2] is not a valid float
         at line 183 in /tmp/binarydeb/ros-foxy-urdfdom-2.3.3/urdf_parser/src/link.cpp
Error:   Could not parse visual element for Link [rod]
         at line 495 in /tmp/binarydeb/ros-foxy-urdfdom-2.3.3/urdf_parser/src/link.cpp
Error:   lower value (-.5) is not a float: stod
         at line 130 in /tmp/binarydeb/ros-foxy-urdfdom-2.3.3/urdf_parser/src/joint.cpp
Error:   Could not parse limit element for joint [tilt]
         at line 565 in /tmp/binarydeb/ros-foxy-urdfdom-2.3.3/urdf_parser/src/joint.cpp
Error:   joint xml is not initialized correctly
         at line 206 in /tmp/binarydeb/ros-foxy-urdfdom-2.3.3/urdf_parser/src/model.cpp

System is Ubuntu 20.04 and ros-foxy.
Can it be that I have to install additional prerequisites ?

**Comment by benbongalon** [comment]
Which version of Rviz2 are you using and how did you install it? I just reran and confirmed it still works (I'm also on 20.02 + Foxy)
![rviz2 2021-01-03 09-29-36](https://user-images.githubusercontent.com/5449663/103484932-5839eb00-4da7-11eb-8f72-5ec3266b137b.png)

**Comment by vkuehn** [comment]
mainly I followed the tutorials. So everthing with apt install  ros-foxy-desktop.
Rviz2 says
This is RViz verion Alpha (ROS 2.0)
Compiled against QT version 5.12.8
Compiled against OGRE Version 1.12.1 (Thagorthua).

**Comment by benbongalon** [comment]
Not sure if it's a virtual box issue. Have you tried loading another URDF model? Here's a tutorial that may help

[Building a Visual Robot Model with URDF from Scratch](http://wiki.ros.org/urdf/Tutorials/Building%20a%20Visual%20Robot%20Model%20with%20URDF%20from%20Scratch)

It's from ROS1, not ROS2 but may carry over without too much tweaks.

**Comment by vkuehn** [comment]
not yet, thought it should just work as it is. I'll look at the tutorial and give an update

**Comment by vkuehn** [comment]
I searched for the problem and others did have it too (not with your example). 
There is nothing when doing a `ros2 topic echo /robot_description`

**Comment by alexbarcelo** [comment]
I am getting the same error as @vkuehn. I am in an Ubuntu 20.04.

I tried to wiggle the floats and add the trailing 0, just in case (i.e. converting ".2" to "0.2") and things changed. At least now rviz2 is showing the legs. So there is some parsing issue maybe?

I stumbled upon this: https://github.com/ros-visualization/rviz/issues/527 but then I checked the date of that issue and it doesn't make sense --moreover that is already fixed.

**Comment by benbongalon** [comment]
Hi Alex,
1. Are you also using virtualbox or another VM?
2. Can you view another URDF model without parsing issues? See link above for a sample model

**Comment by kappa95** [comment]
I get the same issue, I opened an issue [here](https://github.com/ros2/ros2_documentation/issues/1277).

**Comment by kappa95** [comment]
> I searched for the problem and others did have it too (not with your example).
> There is nothing when doing a `ros2 topic echo /robot_description`
> now I get also this
> can't copy 'urdf/model.xml': doesn't exist
> when doing a colcon build --symlink-install

This if you try to rename the file and the code and you try to build again without deleting the old build files, you get the same error

**Comment by kappa95** [comment]
I think to have find the fix (at least for me worked). Change the `locale` into `en_US-UTF-8` as shown in the installing guide of ROS. As I explained in the ros_documentation repository, the parsing fails because for our `locale` the separator for float numbers is comma and not the dot as for the US.

**Comment by alexbarcelo** [comment]
I hate locales :roll_eyes: Yes, that makes sense. I have the main locale as en_US.UTF-8, but a different LC_NUMERIC , which may be responsible for those issues.

Good find @kappa95!

**Comment by vkuehn** [comment]
@alexbarcelo , @kappa95 that would be a part of the tutorials path also. Maybe still worth to change https://github.com/benbongalon/ros2-urdf-tutorial/blob/master/urdf_tutorial/README.md for that if it is really a solution for you both !?
After such a long time I have to find my ROS2 machine again

**Comment by kappa95** [comment]
> @alexbarcelo , @kappa95 that would be a part of the tutorials path also. Maybe still worth to change https://github.com/benbongalon/ros2-urdf-tutorial/blob/master/urdf_tutorial/README.md for that if it is really a solution for you both !?
> After such a long time I have to find my ROS2 machine again

More than an issue for the tutorial itself, it is an "issue" of the urdf parser. Everything works fine with the right locale's settings. It would be better underline on the install tutorial for ROS2 and explain that works on US locale and not a general UTF-8 one.

**Comment by benbongalon** [comment]
@kappa95 great you root caused the problem.

I can update the URDF tutorial to add a tip for resolving the parse errors on non-US locales. But to clarify: should the locale change be made for the entire ROS install or just for the current shell session? I'm hesistant to recommend a global config change that could potential break other modules unless there's consensus that that's the right thing to do.

**Comment by kappa95** [comment]
> @kappa95 great you root caused the problem.
> 
> I can update the URDF tutorial to add a tip for resolving the parse errors on non-US locales. But to clarify: should the locale change be made for the entire ROS install or just for the current shell session? I'm hesistant to recommend a global config change that could potential break other modules unless there's consensus that that's the right thing to do.

When you change the locale, you are changing the setting for the Linux OS. Infact before I have the language in Italian, now in English. But that's all. After doing the changes with `locale` as written in the Install guide of ROS2, you have to reboot the system for having the changes. I notice that after changing the locale, after typing `locale` on the shell I had everything with `IT`, instead if I had typed `sudo locale` I had everything in `en_US`. For that rebooting is necessary for being sure that the changes are done.

**Comment by vkuehn** [comment]
found a fresh vm where the URDF tutorial works now after setting the locales through the tutorials again.

still might be worth changing https://github.com/benbongalon/ros2-urdf-tutorial/blob/master/urdf_tutorial/README.md for that

works me...

**Comment by benbongalon** [comment]
@vkuehn - I added the note at the end of the tutorial. Please confirm it's good then close the ticket. I will also work on pushing the change to the official ROS 2 tutorial.

**Comment by vkuehn** [comment]
that's good. Thanks a lot again for your turoial
