### ISSUE TITLE
Broken URDF and visuals in rviz2

### ISSUE THREAD

**Issue by Thieso** [benbongalon/ros2-urdf-tutorial#3]
Hi, 

I followed the tutorial and it does give me some problems. First of all the float values in the urdf can not be specified by something like .5 instead it has to be 0.5. The leading zero is required otherwise I get an error. 

Secondly, even after fixing that, in Rviz I get wrong visuals in rviz2. I do not know what causes this. I just followed the steps in the tutorial. Is the problem my setup or can someone reproduce it? 

Here is a screenshot of the visuals in rviz2

![image](https://user-images.githubusercontent.com/15210390/113595484-5f3bf800-9639-11eb-82c5-09f05fd10505.png)

**Comment by benbongalon** [comment]
Hi Thies,

From the screenshot, it looks like the model is partially loading (robot
legs). Do you see error messages on rviz?

What OS and Ros version are you using? Also what is your locale value set
to?

Ben

**Comment by Thieso** [comment]
Hi Ben, 

thanks for the quick response. Yes the model is indeed partially loading. But sadly I do not see any error messages in rviz. 

My OS is Kubuntu 20.04 with kernel version 5.8.0-48-generic. 
I use ros foxy. ROS_VERSION just outputs `2` so not sure if that helps. 

The output of `locale -a` is 

```
C
C.UTF-8
de_DE.utf8
en_AG
en_AG.utf8
en_AU.utf8
en_BW.utf8
en_CA.utf8
en_DK.utf8
en_GB.utf8
en_HK.utf8
en_IE.utf8
en_IL
en_IL.utf8
en_IN
en_IN.utf8
en_NG
en_NG.utf8
en_NZ.utf8
en_PH.utf8
en_SG.utf8
en_US.utf8
en_ZA.utf8
en_ZM
en_ZM.utf8
en_ZW.utf8
POSIX
```

Hope this helps

Thies

**Comment by benbongalon** [comment]
I should have been more explicit and asked for your current local settings
(ie, run without the '-a' flag).

The issue is likely with the urdf_parser getting confused with the locale
setting (description here
<https://github.com/ros-visualization/rviz/issues/1151>). Please try
setting

export LC_NUMERIC="en_US.UTF-8"
  (NOTE: export LANG="en_US.UTF-8" also works but the first one is more
specific)

in the console, then rerun rviz again.

**Comment by Thieso** [comment]
Ah my bad sorry, 

But your solution works so thanks a lot. For some reason I didn't find the issue when searching for it. 
Seems like there should be some kind of note somewhere that either resolves this issue or at least triggers some kind of warning since I was rather clueless why this happend. But I will go to the rviz page for that. 

This issue is closed then. Thanks again and stay healthy
